package com.mateo.smart_store_assistant.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDate;

/**
 * Entity representing a product in the store inventory.
 * Maps to the "products" table in the PostgreSQL database.
 */
@Data
@Entity
@Table(name = "products")
public class Product {

    /**
     * Unique identifier for the product, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product. Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Category the product belongs to (e.g. "Dairy", "Beverages"). Cannot be null.
     */
    @Column(nullable = false)
    private String category;

    /**
     * Current stock quantity available in the store. Cannot be null.
     */
    @Column(nullable = false)
    private Integer stock;

    /**
     * Price of the product in DKK. Cannot be null.
     */
    @Column(nullable = false)
    private Double price;

    /**
     * Expiry date of the product. Used to generate expiry alerts.
     */
    @Column(name = "expiry_date")
    private LocalDate expiryDate;
}
